language: c
compiler:
  - gcc
  - clang
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "NEQUeZwTTJ+1Pdy2CpNte1nJLYRY2H8+dpvnGS2HP6U/Ok6ZQm4Zxic+ufhabuymbCV7Jvwwy6Gaj8+ObIDahhzAsiMRXSymnvFHELAnq7DiikJ2HqBvFhPzPI2/vDmEP37msGW1dloipLhdKMeuYYP++BpApnC6KVRVJDXg5JI="
matrix:
  include:
    - compiler: gcc
    - compiler: gcc
      env: CCARG=-std=c89
    - compiler: gcc
      env: CCARG=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
            - libc6:i386
    - compiler: clang
script: ./configure || cat config.log && make check
before_script:
  - export CC="$CC $CCARG"
  - ./bootstrap.sh
sudo: false

addons:
  coverity_scan:
    project:
      name: "kohler/gifsicle"
      description: "Build submitted via Travis CI"
    notification_email: ekohler@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command: "make -j 4"
    branch_pattern: coverity_scan
