name: Build Gifsicle Dynamic Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Clean autotools files
      run: |
        rm -f configure Makefile.in aclocal.m4 src/Makefile.in
        rm -rf autom4te.cache
        rm -f libtool ltmain.sh config.guess config.sub install-sh missing depcomp

    - name: Regenerate autotools files
      run: autoreconf -fiv

    - name: Configure
      run: ./configure --prefix=/usr --disable-shared --enable-static

    - name: Clean previous build
      run: make clean || true

    - name: Build with verbose output
      run: make V=1

    - name: Build shared library manually
      run: |
        cd src
        gcc -shared -fPIC -o libgifsicle.so -DHAVE_CONFIG_H -I. -I.. -I../include \
          libgifsicle.c clp.c fmalloc.c giffunc.c gifread.c gifunopt.c \
          gifwrite.c merge.c optimize.c quantize.c support.c xform.c \
          gifsicle.c kcolor.c -lm

    - name: Check build artifacts
      run: |
        ls -la src/
        ls -la src/.libs/ || echo "No .libs directory found"
        ls -la src/*.so || echo "No .so files found"

    - name: List build artifacts
      run: ls -l src/.libs

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgifsicle-so
        path: src/libgifsicle.so

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
      continue-on-error: true

    - name: Verify MinGW installation
      run: |
        gcc --version
        where gcc

    - name: Copy config file
      run: copy src\win32cfg.h config.h

    - name: Build DLL
      run: |
        cd src
        gcc -shared -o libgifsicle.dll -DHAVE_CONFIG_H -I.. -I../include ^
          libgifsicle.c clp.c fmalloc.c giffunc.c gifread.c gifunopt.c ^
          gifwrite.c merge.c optimize.c quantize.c support.c xform.c ^
          gifsicle.c kcolor.c

    - name: List build artifacts
      run: dir src

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgifsicle-dll
        path: src/libgifsicle.dll