name: Build Gifsicle Dynamic Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Debug environment
      run: |
        pwd
        ls -la
        ls -la include/
        ls -la include/lcdfgif/

    - name: Run bootstrap.sh
      run: ./bootstrap.sh

    - name: Configure
      run: ./configure --prefix=/usr

    - name: Debug Makefile
      run: |
        cd src
        grep "AM_CPPFLAGS" Makefile
        grep "top_srcdir" Makefile

    - name: Build
      run: make

    - name: List build artifacts
      run: ls -l src/.libs

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgifsicle-so
        path: src/.libs/libgifsicle.so

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Copy config file
      run: copy src\win32cfg.h config.h

    - name: Debug Windows environment
      run: |
        dir
        dir include
        dir include\lcdfgif

    - name: Build DLL
      run: |
        cd src
        gcc -shared -o libgifsicle.dll -DHAVE_CONFIG_H -I.. -I../include ^
          clp.c fmalloc.c giffunc.c gifread.c gifunopt.c gifwrite.c ^
          merge.c optimize.c quantize.c support.c xform.c gifsicle.c libgifsicle.c

    - name: List build artifacts
      run: dir src

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgifsicle-dll
        path: src/libgifsicle.dll