name: Build Cross-Platform Libraries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-autotools
          mingw-w64-x86_64-libtool
          autoconf
          automake
          make
    
    - name: Build Windows DLL
      shell: msys2 {0}
      run: |
        autoreconf -fiv
        ./configure
        make
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libgifsicle-windows
        path: |
          src/.libs/*.dll
          src/.libs/libgifsicle.dll.a

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autotools-dev autoconf libtool
    
    - name: Build Linux SO
      run: |
        autoreconf -fiv
        ./configure
        make
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libgifsicle-linux
        path: |
          src/.libs/*.so*
          src/.libs/libgifsicle.a

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install autoconf automake libtool
    
    - name: Build macOS dylib
      run: |
        autoreconf -fiv
        ./configure
        make
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libgifsicle-macos
        path: |
          src/.libs/*.dylib
          src/.libs/libgifsicle.a
