name: Tests

on:
  push:
    branches: [ master, github ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure and build
      run: |
        autoreconf -i
        ./configure

    - name: Make
      run: make

    - name: Run tests
      run: make check
